name: features_counter
description: "This package provides features for demo counter app."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.3.1
  flutter: ^3.19.3

dependencies:
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  cores_navigation:
    path: ../../cores/navigation
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.6.4
  yumemi_lints: ^2.0.0

